name: Build Windows

on:
  workflow_dispatch:

permissions:
  checks: write
  contents: write

env:
  # update here
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_VERSION: 6000.2.8f1
  UNITY_PROJECT_PATH: .

jobs:
  # --- Check Licence ---
  checkLicense:
    name: Check for the Unity License ✅
    runs-on: ubuntu-latest
    steps:
      - name: Fail - No License ☠
        if: ${{ !startsWith(env.UNITY_LICENSE, '<') }}
        run: exit 1

  # --- Test job ---
  test:
    name: Run Unity Tests
    needs: checkLicense
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-test-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-test-

      - uses: game-ci/unity-test-runner@v4
        id: testRunner
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ env.UNITY_PROJECT_PATH }}
          unityVersion: ${{ env.UNITY_VERSION }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test results (all modes)
          path: ${{ steps.testRunner.outputs.artifactsPath }}

  # --- Windows build ---
  build-windows:
    name: Build Windows
    runs-on: windows-2022
    needs: test
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-Windows-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: .
          unityVersion: 6000.2.8f1
          targetPlatform: StandaloneWindows64
          versioning: None

      - uses: actions/upload-artifact@v4
        with:
          name: Build-Windows
          path: build
